name: extract-all

on:
  # Diariamente
  schedule:
  - cron: "30 9 * * *"

  workflow_dispatch:

env:
  CANTIDAD: 8

jobs:
  extract:
    strategy:
      matrix:
        grupo: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
        
      - name: build
        run: go build
        
      - name: run
        run: |
          chmod +x extract.sh
          ./extract.sh ${{ matrix.grupo }} ${{ env.CANTIDAD }}

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.grupo }}
          path: ./*.json
          retention-days: 1
      
          #path: $#{{ matrix.grupo }}.json

      

  merge-save:
    needs: [extract]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
      
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifact-*
          merge-multiple: true

      - name: Consolidar y desplegar datos
        run: MONGO_URI="${{secrets.MONGO_URI}}" go run . deploy

      - name: Guardar datos
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data.json
          retention-days: 90