name: Golang build

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'
 
    - name: Build
      run: |
        cd go
        ls
        go build
        ls

    - name: run
      run: |
        cd go
        ls
        ./sia-extractor 1
