name: test-go

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      group:
        description: 'Grupo'
        required: true
        default: '11'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: "go.sum"
    
    - run: go build

    - name: run
      run: |
        ./sia-extractor ${{ github.event.inputs.group }}
        ls

    - name: Guardar datos
      uses: actions/upload-artifact@v4
      with:
        name: test-data
        path: ${{ github.event.inputs.group }}.json
        retention-days: 1