name: start

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.0"

      - name: Instalar dependencias
        run: npm install

      - name: Extraer datos
        run: node .