name: test-all

on:
  workflow_dispatch:

jobs:
  extract:
    strategy:
      fail-fast: false
      matrix:
        grupo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"

      - name: build
        run: go build
      
      - name: run
        run: ./sia-extractor test ${{ matrix.grupo }}

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.grupo }}
          path: ${{ matrix.grupo }}.json
          retention-days: 1