name: test

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
      
      - name: build
        run: go build

      - name: parallel
        run: sudo apt-get install parallel

      - name: run
        run: |
          parallel -j 15 --ungroup './sia-extractor extract {1}' ::: {1..15}